title: Site
tabs:
  pages:
    columns:
      - width: 1/3
        sections:
          unlistedPages:
            image: false
            headline: Core Pages
            type: pages
            status: unlisted
      - width: 1/3
        sections:
          listedPages:
            image: false
            headline: Listed Pages
            type: pages
            status: listed
      - width: 1/3
        sections:
          draftPages:
            image: false
            headline: Draft Pages
            type: pages
            status: draft

  settings:
    label: Settings
    columns:
      - width: 2/3
        fields:
          description:
            label: Description
            type:  textarea
            buttons: false
            maxlength: 200
            size: tiny
            help: A short summary to give people an idea of what to expect when visiting your website.
          keywords:
            label: Keywords
            size: tiny
            type:  tags
            help: Keywords to help search engines index your website.
          ogImage:
            label: Social Image
            type: files
            uploads: image
            multiple: false
            layout: cards
            help: 1200 x 630px recommended<br>This image is the first thing people will see when someone shares your website.
          logoImage:
            label: Logo
            type: files
            uploads: image
            multiple: false
            layout: cards
            help: Square image used as logo in the header for the site.
            width: 1/3
          faviconImage:
            label: Favicon Icon
            type: files
            uploads: image
            multiple: false
            layout: cards
            help: 192 x 192px png<br>Square image used as global icon for the site.
            width: 1/3
          touchImage:
            label: Touch Icon
            type: files
            uploads: image
            multiple: false
            layout: cards
            help: 180 x 180px png<br>Square image used as touch icon for the site.
            width: 1/3
      - width: 1/3
        fields:
          facebookPixelID:
            label: Facebook Pixel ID
            type: text
            type: hidden
            help: For facebook tracking
          googleAnalyticsID:
            label: Google Analytics ID
            type: text
            icon: code
            placeholder: UA-XXXXXXXX-X
            help: Tracking ID in the form UA-XXXXXXXX-X<br>Keep this field empty if you are not using it.
          instagramName:
            label: Instagram Name
            type: text
            placeholder: accountname
          telephone:
            label: Telephone
            type: text
          email:
            label: Main Contact Email
            type: email
          address:
            label: Address
            buttons: false
            size: tiny
            type: textarea
          linkInstagram: linkInstagram
            
          
  # matomo:
  #   label: Matomo Tracking
  #   columns:
  #     - width: 1
  #       fields:
  #         matomourl:
  #           label: Matomo URL
  #           type: text
  #           width: 1/3
  #         matomoid:
  #           label: Matomo ID
  #           type: text
  #           width: 1/3
  #         matomotoken:
  #           label: Matomo Authentication Token
  #           type: text
  #           width: 1/3
  #     - width: 3/4
  #       sections:
  #         main:
  #           type: matomo-main
  #     - width: 1/4
  #       sections:
  #         sidebar:
  #           type: matomo-sidebar

  files:
    sections:
      fileuploader:
        extends: sections/uploader
